CREATE PROCEDURE insert_zsalestransaction(
    IN BUSINESSUNITNAME NVARCHAR(255), 
    IN CHANNEL NVARCHAR(255), 
    IN COMMENTS NVARCHAR(255),
    IN COMPENSATIONDATE DATE,  
    IN EVENTTYPE NVARCHAR(255),
    IN GENERICATTRIBUTE1 NVARCHAR(255),
    IN GENERICATTRIBUTE12 NVARCHAR(255),
    IN GENERICATTRIBUTE2 NVARCHAR(255),
    IN GENERICATTRIBUTE27 NVARCHAR(255),
    IN GENERICATTRIBUTE3 NVARCHAR(255),
    IN ISRUNNABLE SMALLINT,
    IN LINENUMBER BIGINT,
    IN ORDERID NVARCHAR(255),
    IN ORIGINTYPEID NVARCHAR(255),
    IN PREADJUSTEDVALUE DECIMAL(18, 2),
    IN PRODUCTID NVARCHAR(255),
    IN SUBLINENUMBER BIGINT,
    IN TENANTID NVARCHAR(255),
    IN UNITTYPEFORLINENUMBER NVARCHAR(255),
    IN UNITTYPEFORPREADJUSTEDVALUE NVARCHAR(255),
    IN UNITTYPEFORSUBLINENUMBER NVARCHAR(255),
    IN UNITTYPEFORVALUE NVARCHAR(255),
    IN VALUE DECIMAL(18, 2),
    OUT SALESTRANSACTIONSEQ INT
)
LANGUAGE SQLSCRIPT
AS
BEGIN

	

    INSERT INTO ZSALESTRANSACTION
    (
        BUSINESSUNITNAME, CHANNEL, COMMENTS, COMPENSATIONDATE, EVENTTYPE, GENERICATTRIBUTE1, 
        GENERICATTRIBUTE12, GENERICATTRIBUTE2, GENERICATTRIBUTE27, GENERICATTRIBUTE3, ISRUNNABLE, 
        LINENUMBER, ORDERID, ORIGINTYPEID, PREADJUSTEDVALUE, PRODUCTID, SUBLINENUMBER, TENANTID, 
        UNITTYPEFORLINENUMBER, UNITTYPEFORPREADJUSTEDVALUE, UNITTYPEFORSUBLINENUMBER, UNITTYPEFORVALUE, VALUE,MODIFICATIONDATE
    )
    VALUES
    (
        BUSINESSUNITNAME, CHANNEL, COMMENTS, COMPENSATIONDATE, EVENTTYPE, GENERICATTRIBUTE1, 
        GENERICATTRIBUTE12, GENERICATTRIBUTE2, GENERICATTRIBUTE27, GENERICATTRIBUTE3, ISRUNNABLE, 
        LINENUMBER, ORDERID, ORIGINTYPEID, PREADJUSTEDVALUE, PRODUCTID, SUBLINENUMBER, TENANTID, 
        UNITTYPEFORLINENUMBER, UNITTYPEFORPREADJUSTEDVALUE, UNITTYPEFORSUBLINENUMBER, UNITTYPEFORVALUE, VALUE,CURRENT_DATE
    );


    SELECT CURRENT_IDENTITY_VALUE() INTO SALESTRANSACTIONSEQ FROM DUMMY;

END;