CREATE PROCEDURE "HABIB".pro_MOVE_and_DEL_TR_LIST_SMS(
    IN salestransaction BIGINT
)
LANGUAGE SQLSCRIPT
AS
BEGIN
    -- Define the CTE to get the joined data
    CREATE LOCAL TEMPORARY TABLE #TempJoinedData (
        "BUSINESSUNITNAME" VARCHAR(127),
        "CHANNEL" VARCHAR(20),
        "COMMENTS" VARCHAR(255),
        "COMPENSATIONDATE" DATE,
        "EVENTTYPE" VARCHAR(40),
        "GENERICATTRIBUTE1" VARCHAR(255),
        "GENERICATTRIBUTE2" VARCHAR(255),
        "GENERICATTRIBUTE3" VARCHAR(255),
        "GENERICATTRIBUTE6" VARCHAR(255),
        "GENERICATTRIBUTE12" VARCHAR(255),
        "GENERICATTRIBUTE27" VARCHAR(255),
        "GENERICATTRIBUTE28" VARCHAR(255),
        "GENERICATTRIBUTE29" VARCHAR(255),
        "GENERICATTRIBUTE30" VARCHAR(255),
        "GENERICATTRIBUTE31" VARCHAR(255),
        "GENERICBOOLEAN1" SMALLINT,
        "GENERICBOOLEAN2" SMALLINT,
        "GENERICNUMBER1" DECIMAL(25, 10),
        "GENERICNUMBER2" DECIMAL(25, 10),
        "GENERICNUMBER3" DECIMAL(25, 10),
        "GENERICNUMBER4" DECIMAL(25, 10),
        "GENERICNUMBER5" DECIMAL(25, 10),
        "ISRUNNABLE" SMALLINT,
        "LINENUMBER" BIGINT,
        "MODIFICATIONDATE" LONGDATE,
        "ORDERID" VARCHAR(40),
        "ORIGINTYPEID" VARCHAR(10),
        "PREADJUSTEDVALUE" DECIMAL(25, 10),
        "PRODUCTID" VARCHAR(127),
        "SALESTRANSACTIONSEQ" BIGINT,
        "SUBLINENUMBER" BIGINT,
        "TENANTID" VARCHAR(100),
        "UNITTYPEFORLINENUMBER" VARCHAR(40),
        "UNITTYPEFORPREADJUSTEDVALUE" VARCHAR(40),
        "UNITTYPEFORSUBLINENUMBER" VARCHAR(40),
        "UNITTYPEFORVALUE" VARCHAR(40),
        "UNITTYPEFORGENERICNUMBER1" VARCHAR(40),
        "UNITTYPEFORGENERICNUMBER2" VARCHAR(40),
        "UNITTYPEFORGENERICNUMBER3" VARCHAR(40),
        "UNITTYPEFORGENERICNUMBER4" VARCHAR(40),
        "UNITTYPEFORGENERICNUMBER5" VARCHAR(40),
         "VALUE" DECIMAL(25, 10)
    );

    -- Insert data into temporary table
    INSERT INTO #TempJoinedData (
        "BUSINESSUNITNAME", "CHANNEL", "COMMENTS", "COMPENSATIONDATE", "EVENTTYPE", "GENERICATTRIBUTE1", 
        "GENERICATTRIBUTE12", "GENERICATTRIBUTE2",  "GENERICATTRIBUTE27", "GENERICATTRIBUTE28", 
        "GENERICATTRIBUTE29", "GENERICATTRIBUTE3", "GENERICATTRIBUTE30","GENERICATTRIBUTE6",
        "GENERICNUMBER1", "GENERICNUMBER2", "GENERICNUMBER3", "GENERICNUMBER4", "GENERICNUMBER5",  "ISRUNNABLE", "LINENUMBER", "MODIFICATIONDATE", "ORDERID", "ORIGINTYPEID", "PREADJUSTEDVALUE", 
        "PRODUCTID",  "SALESTRANSACTIONSEQ", "SUBLINENUMBER", "TENANTID", 
        "UNITTYPEFORLINENUMBER", 
        "UNITTYPEFORPREADJUSTEDVALUE", "UNITTYPEFORSUBLINENUMBER", "UNITTYPEFORVALUE", "VALUE","UNITTYPEFORGENERICNUMBER1","UNITTYPEFORGENERICNUMBER2","UNITTYPEFORGENERICNUMBER3","UNITTYPEFORGENERICNUMBER4","UNITTYPEFORGENERICNUMBER5",
        "GENERICATTRIBUTE31","GENERICBOOLEAN1","GENERICBOOLEAN2"
    ) 
    SELECT 
        zt.BUSINESSUNITNAME, zt.CHANNEL, zt.COMMENTS, zt.COMPENSATIONDATE, zters.EVENTTYPE,
        zt.GENERICATTRIBUTE1, zt.GENERICATTRIBUTE12, zt.GENERICATTRIBUTE2, 
        'MOVED' AS GENERICATTRIBUTE27, ztcalc.GENERICATTRIBUTE28,
        ztcalc.GENERICATTRIBUTE29, zt.GENERICATTRIBUTE3, ztcalc.GENERICATTRIBUTE30,
        zters.GENERICATTRIBUTE6, ztcalc.GENERICNUMBER1, ztcalc.GENERICNUMBER2,
        ztcalc.GENERICNUMBER3, ztcalc.GENERICNUMBER4, ztcalc.GENERICNUMBER5, 
        zt.ISRUNNABLE, zters.LINENUMBER, zt.MODIFICATIONDATE,
        zters.ORDERID, zt.ORIGINTYPEID, zt.PREADJUSTEDVALUE, zt.PRODUCTID, 
        zters.SALESTRANSACTIONSEQ, zters.SUBLINENUMBER, zt.TENANTID, 
        zt.UNITTYPEFORLINENUMBER, zt.UNITTYPEFORPREADJUSTEDVALUE,
        zt.UNITTYPEFORSUBLINENUMBER, zt.UNITTYPEFORVALUE, zt.VALUE,
        ztcalc.UNITTYPEFORGENERICNUMBER1, ztcalc.UNITTYPEFORGENERICNUMBER2,
        ztcalc.UNITTYPEFORGENERICNUMBER3, ztcalc.UNITTYPEFORGENERICNUMBER4,
        ztcalc.UNITTYPEFORGENERICNUMBER5, ztcalc.GENERICATTRIBUTE31,
        ztcalc.GENERICBOOLEAN1, ztcalc.GENERICBOOLEAN2
    FROM 
        zsalestransaction_ers zters
    JOIN 
        zsalestransaction zt ON zters.salestransactionseq = zt.salestransactionseq
    JOIN 
        zsalestransaction_calc ztcalc ON zters.salestransactionseq = ztcalc.salestransactionseq
    WHERE 
        zters.GENERICATTRIBUTE27 = 'SERS' AND zters.SALESTRANSACTIONSEQ = salestransaction;

    -- Insert into ZSALESTRANSACTION_LIST
    INSERT INTO ZSALESTRANSACTION_LIST (
        "BUSINESSUNITNAME", "CHANNEL", "COMMENTS", "COMPENSATIONDATE", "EVENTTYPE", "GENERICATTRIBUTE1", 
        "GENERICATTRIBUTE12", "GENERICATTRIBUTE2",  "GENERICATTRIBUTE27", "GENERICATTRIBUTE28", 
        "GENERICATTRIBUTE29", "GENERICATTRIBUTE3", "GENERICATTRIBUTE30","GENERICATTRIBUTE6",
        "GENERICNUMBER1", "GENERICNUMBER2", "GENERICNUMBER3", "GENERICNUMBER4", "GENERICNUMBER5",  "ISRUNNABLE", "LINENUMBER", "MODIFICATIONDATE", "ORDERID", "ORIGINTYPEID", "PREADJUSTEDVALUE", 
        "PRODUCTID",  "SALESTRANSACTIONSEQ", "SUBLINENUMBER", "TENANTID", 
        "UNITTYPEFORLINENUMBER", 
        "UNITTYPEFORPREADJUSTEDVALUE", "UNITTYPEFORSUBLINENUMBER", "UNITTYPEFORVALUE", "VALUE","UNITTYPEFORGENERICNUMBER1","GENERICATTRIBUTE22","GENERICATTRIBUTE23","GENERICATTRIBUTE24","GENERICATTRIBUTE25",
        "GENERICATTRIBUTE31","GENERICBOOLEAN1","GENERICBOOLEAN2"
    )
    SELECT 
        BUSINESSUNITNAME, CHANNEL, COMMENTS, COMPENSATIONDATE, EVENTTYPE, GENERICATTRIBUTE1, 
        GENERICATTRIBUTE12, GENERICATTRIBUTE2,  GENERICATTRIBUTE27, GENERICATTRIBUTE28, 
        GENERICATTRIBUTE29, GENERICATTRIBUTE3, GENERICATTRIBUTE30, GENERICATTRIBUTE6,
        GENERICNUMBER1, GENERICNUMBER2, GENERICNUMBER3, GENERICNUMBER4, GENERICNUMBER5,  
        ISRUNNABLE, LINENUMBER, MODIFICATIONDATE, ORDERID, ORIGINTYPEID, PREADJUSTEDVALUE, 
        PRODUCTID,  SALESTRANSACTIONSEQ, SUBLINENUMBER, TENANTID, 
        UNITTYPEFORLINENUMBER, UNITTYPEFORPREADJUSTEDVALUE, UNITTYPEFORSUBLINENUMBER, UNITTYPEFORVALUE, 
        VALUE, UNITTYPEFORGENERICNUMBER1,UNITTYPEFORGENERICNUMBER2, UNITTYPEFORGENERICNUMBER3, UNITTYPEFORGENERICNUMBER4, UNITTYPEFORGENERICNUMBER5,
        GENERICATTRIBUTE31, GENERICBOOLEAN1, GENERICBOOLEAN2
    FROM #TempJoinedData;

    -- Insert into ZSMS
    INSERT INTO ZSMS ( 
        "CHANNEL", "COMMENTS", "COMPENSATIONDATE", "EVENTTYPE", "GENERICATTRIBUTE1", 
        "GENERICATTRIBUTE27", "GENERICATTRIBUTE28", "GENERICATTRIBUTE29", "GENERICATTRIBUTE30",
        "GENERICNUMBER1", "GENERICNUMBER2", "GENERICNUMBER3", "GENERICNUMBER4", "GENERICNUMBER5", 
        "LINENUMBER", "MODIFICATIONDATE", "ORDERID", "PRODUCTID",  "SALESTRANSACTIONSEQ", 
        "SUBLINENUMBER", "TENANTID", "UNITTYPEFORLINENUMBER", "UNITTYPEFORSUBLINENUMBER", 
        "UNITTYPEFORVALUE", "VALUE", "UNITTYPEFORGENERICNUMBER1", "UNITTYPEFORGENERICNUMBER2",
        "UNITTYPEFORGENERICNUMBER3", "UNITTYPEFORGENERICNUMBER4", "UNITTYPEFORGENERICNUMBER5",
        "GENERICATTRIBUTE31"
    )
    SELECT 
        CHANNEL, COMMENTS, COMPENSATIONDATE, EVENTTYPE, GENERICATTRIBUTE1, 
        GENERICATTRIBUTE27, GENERICATTRIBUTE28, GENERICATTRIBUTE29,GENERICATTRIBUTE30, 
        GENERICNUMBER1, GENERICNUMBER2, GENERICNUMBER3, GENERICNUMBER4, GENERICNUMBER5,   
        LINENUMBER, MODIFICATIONDATE, ORDERID, PRODUCTID, SALESTRANSACTIONSEQ, SUBLINENUMBER, 
        TENANTID, UNITTYPEFORLINENUMBER, UNITTYPEFORSUBLINENUMBER, UNITTYPEFORVALUE, VALUE, 
        UNITTYPEFORGENERICNUMBER1, UNITTYPEFORGENERICNUMBER2, UNITTYPEFORGENERICNUMBER3, 
        UNITTYPEFORGENERICNUMBER4, UNITTYPEFORGENERICNUMBER5, GENERICATTRIBUTE31
    FROM #TempJoinedData;
    
    -- Drop the temporary table
    DROP TABLE #TempJoinedData;

END;