CREATE PROCEDURE HABIB.reprocess_ers_posted(
    IN salestransaction BIGINT,
    IN p_order_id VARCHAR(40),
    IN p_event_type VARCHAR(40),
    IN p_linenumber BIGINT,
    IN p_sublinenumber BIGINT,
    IN corelationid NVARCHAR(255),
    IN resultcode NVARCHAR(10),
    IN error NVARCHAR(255)
)
LANGUAGE SQLSCRIPT
AS
BEGIN
    DECLARE new_status NVARCHAR(10);
    DECLARE COUNT_ERROR SMALLINT;
    
    
    
    DECLARE EXIT HANDLER FOR SQLEXCEPTION
    BEGIN
        DECLARE error_msg NVARCHAR(5000);
        DECLARE error_msg1 NVARCHAR(5000);
        
         SELECT ::SQL_ERROR_MESSAGE INTO error_msg FROM DUMMY;
         
         error_msg1 = error_msg;
         
          DELETE FROM ZSALESTRANSACTION_ERROR WHERE "SALESTRANSACTIONSEQ" = salestransaction;
        
          -- Insert into the error log table
        INSERT INTO ZSALESTRANSACTION_ERROR
    (
        SALESTRANSACTIONSEQ,BUSINESSUNITNAME, CHANNEL, COMMENTS, COMPENSATIONDATE, EVENTTYPE, GENERICATTRIBUTE1, 
        GENERICATTRIBUTE12, GENERICATTRIBUTE2, GENERICATTRIBUTE27, GENERICATTRIBUTE3, ISRUNNABLE, 
        LINENUMBER, ORDERID, ORIGINTYPEID, PREADJUSTEDVALUE, PRODUCTID, SUBLINENUMBER, TENANTID, 
        UNITTYPEFORLINENUMBER, UNITTYPEFORPREADJUSTEDVALUE, UNITTYPEFORSUBLINENUMBER, UNITTYPEFORVALUE,
         VALUE,MODIFICATIONDATE,ERROR_MSG,GENERICATTRIBUTE28,GENERICATTRIBUTE29,GENERICATTRIBUTE30,
       	GENERICNUMBER1,GENERICNUMBER2,GENERICNUMBER3,GENERICNUMBER4,GENERICNUMBER5,GENERICATTRIBUTE6,
       	GENERICATTRIBUTE22,GENERICATTRIBUTE23,GENERICATTRIBUTE24,GENERICATTRIBUTE25,GENERICATTRIBUTE31,GENERICBOOLEAN1,GENERICBOOLEAN2
    )
    SELECT
    	salestransaction,
        T."BUSINESSUNITNAME",
         T."CHANNEL",
          T."COMMENTS",
           T."COMPENSATIONDATE",
            T."EVENTTYPE", 
            T."GENERICATTRIBUTE1",
             T."GENERICATTRIBUTE12",
              T."GENERICATTRIBUTE2",
               'ERROR ERS',
                T."GENERICATTRIBUTE3",
                 T."ISRUNNABLE", 
        T."LINENUMBER",
         T."ORDERID",
          T."ORIGINTYPEID",
           T."PREADJUSTEDVALUE", 
           T."PRODUCTID",
            T."SUBLINENUMBER",
             T."TENANTID", 
       T."UNITTYPEFORLINENUMBER",
         T."UNITTYPEFORPREADJUSTEDVALUE",
          T."UNITTYPEFORSUBLINENUMBER",
           T."UNITTYPEFORVALUE",
         T."VALUE",
         CURRENT_DATE,
         error_msg1,
          T."GENERICATTRIBUTE28",
          T."GENERICATTRIBUTE29",
           T."GENERICATTRIBUTE30",
           T."GENERICNUMBER1",
           T."GENERICNUMBER2",
            T."GENERICNUMBER3",
             T."GENERICNUMBER4",
             T."GENERICNUMBER5",
             corelationid,
              T."GENERICATTRIBUTE22",
             T."GENERICATTRIBUTE23",
             T."GENERICATTRIBUTE24",
             T."GENERICATTRIBUTE25",
             T."GENERICATTRIBUTE31",
             T."GENERICBOOLEAN1",
             T."GENERICBOOLEAN2"
    FROM ZSALESTRANSACTION_CALC AS T
     WHERE 
        	T."SALESTRANSACTIONSEQ" = salestransaction;
        
        
      
    END;
    
    


    -- Determine the new status based on resultcode
    IF resultcode = 'EIL000' THEN
        new_status = 'SERS';
        -- Update the table
		 INSERT INTO HABIB.ZSALESTRANSACTION_ERS (SALESTRANSACTIONSEQ,ORDERID,EVENTTYPE,LINENUMBER,SUBLINENUMBER,GENERICATTRIBUTE27,GENERICATTRIBUTE6)
         
            VALUES(
            salestransaction,
             p_order_id,
             p_event_type,
             p_linenumber,
             p_sublinenumber,      
             new_status,
             corelationid);
             
             
             delete from zsalestransaction_error where SALESTRANSACTIONSEQ = salestransaction;
             
    ELSE
        new_status = 'NERS';
        
        
        SELECT COUNT(*) INTO COUNT_ERROR FROM ZSALESTRANSACTION_ERROR WHERE "SALESTRANSACTIONSEQ" = SALESTRANSACTION;

      

      IF COUNT_ERROR > 0 THEN

      

      

      delete from zsalestransaction_error where SALESTRANSACTIONSEQ = salestransaction;

      
        
         INSERT INTO ZSALESTRANSACTION_ERROR
    (
        SALESTRANSACTIONSEQ,BUSINESSUNITNAME, CHANNEL, COMMENTS, COMPENSATIONDATE, EVENTTYPE, GENERICATTRIBUTE1, 
        GENERICATTRIBUTE12, GENERICATTRIBUTE2, GENERICATTRIBUTE27, GENERICATTRIBUTE3, ISRUNNABLE, 
        LINENUMBER, ORDERID, ORIGINTYPEID, PREADJUSTEDVALUE, PRODUCTID, SUBLINENUMBER, TENANTID, 
        UNITTYPEFORLINENUMBER, UNITTYPEFORPREADJUSTEDVALUE, UNITTYPEFORSUBLINENUMBER, UNITTYPEFORVALUE,
         VALUE,MODIFICATIONDATE,GENERICATTRIBUTE28,GENERICATTRIBUTE29,GENERICATTRIBUTE30,
       	GENERICNUMBER1,GENERICNUMBER2,GENERICNUMBER3,GENERICNUMBER4,GENERICNUMBER5,GENERICATTRIBUTE6,
       	GENERICATTRIBUTE22,GENERICATTRIBUTE23,GENERICATTRIBUTE24,GENERICATTRIBUTE25,GENERICATTRIBUTE31,GENERICBOOLEAN1,GENERICBOOLEAN2,ERROR_MSG
    )
    SELECT
    	salestransaction,
        T."BUSINESSUNITNAME",
         T."CHANNEL",
          T."COMMENTS",
           T."COMPENSATIONDATE",
            T."EVENTTYPE", 
            T."GENERICATTRIBUTE1",
             T."GENERICATTRIBUTE12",
              T."GENERICATTRIBUTE2",
               new_status,
                T."GENERICATTRIBUTE3",
                 T."ISRUNNABLE", 
        T."LINENUMBER",
         T."ORDERID",
          T."ORIGINTYPEID",
           T."PREADJUSTEDVALUE", 
           T."PRODUCTID",
            T."SUBLINENUMBER",
             T."TENANTID", 
       T."UNITTYPEFORLINENUMBER",
         T."UNITTYPEFORPREADJUSTEDVALUE",
          T."UNITTYPEFORSUBLINENUMBER",
           T."UNITTYPEFORVALUE",
         T."VALUE",
         CURRENT_DATE,
          T."GENERICATTRIBUTE28",
          T."GENERICATTRIBUTE29",
           T."GENERICATTRIBUTE30",
           T."GENERICNUMBER1",
           T."GENERICNUMBER2",
            T."GENERICNUMBER3",
             T."GENERICNUMBER4",
             T."GENERICNUMBER5",
             corelationid,
              T."GENERICATTRIBUTE22",
             T."GENERICATTRIBUTE23",
             T."GENERICATTRIBUTE24",
             T."GENERICATTRIBUTE25",
             T."GENERICATTRIBUTE31",
             T."GENERICBOOLEAN1",
             T."GENERICBOOLEAN2",	
             error
    FROM ZSALESTRANSACTION_CALC AS T
     WHERE 
        	T."SALESTRANSACTIONSEQ" = salestransaction;
    END IF;
   END IF;
   
	
	
END;