CREATE PROCEDURE HABIB.reprocess_pro_MOVE_and_DEL_TR(
OUT result_data TABLE (
    "BUSINESSUNITNAME" VARCHAR(127),
        "CHANNEL" VARCHAR(20),
        "COMMENTS" VARCHAR(255),
        "COMPENSATIONDATE" DATE,
        "EVENTTYPE" VARCHAR(40),
        "GENERICATTRIBUTE1" VARCHAR(255),
        "GENERICATTRIBUTE12" VARCHAR(255),
        "GENERICATTRIBUTE2" VARCHAR(255),
        "GENERICATTRIBUTE27" VARCHAR(255),
        "GENERICATTRIBUTE22" VARCHAR(255),
        "GENERICATTRIBUTE23" VARCHAR(255),
        "GENERICATTRIBUTE24" VARCHAR(255),
        "GENERICATTRIBUTE25" VARCHAR(255),
        "GENERICATTRIBUTE28" VARCHAR(255),
        "GENERICATTRIBUTE31" VARCHAR(255),
        "GENERICBOOLEAN1" SMALLINT,
        "GENERICBOOLEAN2" SMALLINT,
        "GENERICATTRIBUTE29" VARCHAR(255),
        "GENERICATTRIBUTE3" VARCHAR(255),
        "GENERICATTRIBUTE30" VARCHAR(255),
        "GENERICATTRIBUTE6" VARCHAR(255),
        "GENERICNUMBER1" DECIMAL(25, 10),
        "GENERICNUMBER2" DECIMAL(25, 10),
        "GENERICNUMBER3" DECIMAL(25, 10),
        "GENERICNUMBER4" DECIMAL(25, 10),
        "GENERICNUMBER5" DECIMAL(25, 10),
        "ISRUNNABLE" SMALLINT,
        "LINENUMBER" BIGINT,
        "MODIFICATIONDATE" LONGDATE,
        "ORDERID" VARCHAR(40),
        "ORIGINTYPEID" VARCHAR(10),
        "PREADJUSTEDVALUE" DECIMAL(25, 10),
        "PRODUCTID" VARCHAR(127),
        "SALESTRANSACTIONSEQ" BIGINT,
        "SUBLINENUMBER" BIGINT,
        "TENANTID" VARCHAR(100),
        "UNITTYPEFORLINENUMBER" VARCHAR(40),
        "UNITTYPEFORPREADJUSTEDVALUE" VARCHAR(40),
        "UNITTYPEFORSUBLINENUMBER" VARCHAR(40),
        "UNITTYPEFORVALUE" VARCHAR(40),
        "VALUE" DECIMAL(25, 10),
        "UNITTYPEFORGENERICNUMBER1" VARCHAR(40),
        "UNITTYPEFORGENERICNUMBER2" VARCHAR(40),
        "UNITTYPEFORGENERICNUMBER3" VARCHAR(40),
        "UNITTYPEFORGENERICNUMBER4" VARCHAR(40),
        "UNITTYPEFORGENERICNUMBER5" VARCHAR(40)
    )
    )
LANGUAGE SQLSCRIPT
AS
BEGIN
	    
    DECLARE CURSOR cur FOR 
    SELECT * from zsalestransaction_error
WHERE 
    "GENERICATTRIBUTE27" = 'NOT MOVED';
    
    
    
    create local temporary table #temp_table (
        "BUSINESSUNITNAME" VARCHAR(127),
        "CHANNEL" VARCHAR(20),
        "COMMENTS" VARCHAR(255),
        "COMPENSATIONDATE" DATE,
        "EVENTTYPE" VARCHAR(40),
        "GENERICATTRIBUTE1" VARCHAR(255),
        "GENERICATTRIBUTE12" VARCHAR(255),
        "GENERICATTRIBUTE2" VARCHAR(255),
        "GENERICATTRIBUTE27" VARCHAR(255),
        "GENERICATTRIBUTE22" VARCHAR(255),
        "GENERICATTRIBUTE23" VARCHAR(255),
        "GENERICATTRIBUTE24" VARCHAR(255),
        "GENERICATTRIBUTE25" VARCHAR(255),
        "GENERICATTRIBUTE28" VARCHAR(255),
        "GENERICATTRIBUTE31" VARCHAR(255),
        "GENERICBOOLEAN1" SMALLINT,
        "GENERICBOOLEAN2" SMALLINT,
        "GENERICATTRIBUTE29" VARCHAR(255),
        "GENERICATTRIBUTE3" VARCHAR(255),
        "GENERICATTRIBUTE30" VARCHAR(255),
        "GENERICATTRIBUTE6" VARCHAR(255),
        "GENERICNUMBER1" DECIMAL(25, 10),
        "GENERICNUMBER2" DECIMAL(25, 10),
        "GENERICNUMBER3" DECIMAL(25, 10),
        "GENERICNUMBER4" DECIMAL(25, 10),
        "GENERICNUMBER5" DECIMAL(25, 10),
        "ISRUNNABLE" SMALLINT,
        "LINENUMBER" BIGINT,
        "MODIFICATIONDATE" LONGDATE,
        "ORDERID" VARCHAR(40),
        "ORIGINTYPEID" VARCHAR(10),
        "PREADJUSTEDVALUE" DECIMAL(25, 10),
        "PRODUCTID" VARCHAR(127),
        "SALESTRANSACTIONSEQ" BIGINT,
        "SUBLINENUMBER" BIGINT,
        "TENANTID" VARCHAR(100),
        "UNITTYPEFORLINENUMBER" VARCHAR(40),
        "UNITTYPEFORPREADJUSTEDVALUE" VARCHAR(40),
        "UNITTYPEFORSUBLINENUMBER" VARCHAR(40),
        "UNITTYPEFORVALUE" VARCHAR(40),
        "VALUE" DECIMAL(25, 10),
        "UNITTYPEFORGENERICNUMBER1" VARCHAR(40),
        "UNITTYPEFORGENERICNUMBER2" VARCHAR(40),
        "UNITTYPEFORGENERICNUMBER3" VARCHAR(40),
        "UNITTYPEFORGENERICNUMBER4" VARCHAR(40),
        "UNITTYPEFORGENERICNUMBER5" VARCHAR(40)
    );

    -- Open the cursor
    OPEN cur;

    -- Loop through each record
    FOR rec AS cur DO
        DECLARE CONTINUE HANDLER FOR SQLEXCEPTION
        BEGIN
        
        DECLARE error_msg NVARCHAR(5000);
         DECLARE error_msg1 NVARCHAR(5000);
        
         SELECT ::SQL_ERROR_MESSAGE INTO error_msg FROM DUMMY;
         
         error_msg1 = error_msg;
         
         DELETE FROM HABIB.ZSALESTRANSACTION_ERROR
        WHERE "SALESTRANSACTIONSEQ" = rec."SALESTRANSACTIONSEQ" ;
        
            INSERT INTO ZSALESTRANSACTION_ERROR (
            "BUSINESSUNITNAME", "CHANNEL", "COMMENTS", "COMPENSATIONDATE", "EVENTTYPE", "GENERICATTRIBUTE1", 
              "GENERICATTRIBUTE12", "GENERICATTRIBUTE2",  "GENERICATTRIBUTE27", "GENERICATTRIBUTE28", 
            "GENERICATTRIBUTE29", "GENERICATTRIBUTE3", "GENERICATTRIBUTE30","GENERICATTRIBUTE6",
            "GENERICNUMBER1", "GENERICNUMBER2", "GENERICNUMBER3", "GENERICNUMBER4", "GENERICNUMBER5",  "ISRUNNABLE", "LINENUMBER", "MODIFICATIONDATE", "ORDERID", "ORIGINTYPEID", "PREADJUSTEDVALUE", 
             "PRODUCTID",  "SALESTRANSACTIONSEQ", "SUBLINENUMBER", "TENANTID", 
             "UNITTYPEFORLINENUMBER", 
            "UNITTYPEFORPREADJUSTEDVALUE", "UNITTYPEFORSUBLINENUMBER", "UNITTYPEFORVALUE", "VALUE","ERROR_MSG","UNITTYPEFORGENERICNUMBER1","UNITTYPEFORGENERICNUMBER2","UNITTYPEFORGENERICNUMBER3","UNITTYPEFORGENERICNUMBER4","UNITTYPEFORGENERICNUMBER5",
            "GENERICATTRIBUTE22","GENERICATTRIBUTE23","GENERICATTRIBUTE24","GENERICATTRIBUTE25","GENERICATTRIBUTE31","GENERICBOOLEAN1","GENERICBOOLEAN2"
        )
        VALUES (
            rec."BUSINESSUNITNAME",
            rec."CHANNEL",
            rec."COMMENTS",
            rec."COMPENSATIONDATE", 
            rec."EVENTTYPE", 
            rec."GENERICATTRIBUTE1", 
            rec."GENERICATTRIBUTE12",
            rec."GENERICATTRIBUTE2",
            'NOT MOVED', 
            rec."GENERICATTRIBUTE28", 
            rec."GENERICATTRIBUTE29", 
            rec."GENERICATTRIBUTE3", 
            rec."GENERICATTRIBUTE30",
            rec."GENERICATTRIBUTE6",
            rec."GENERICNUMBER1", 
            rec."GENERICNUMBER2", 
            rec."GENERICNUMBER3", 
            rec."GENERICNUMBER4", 
            rec."GENERICNUMBER5", 
            rec."ISRUNNABLE", 
            rec."LINENUMBER", 
            rec."MODIFICATIONDATE", 
            rec."ORDERID", 
            rec."ORIGINTYPEID", 
            rec."PREADJUSTEDVALUE",
            rec."PRODUCTID",
            rec."SALESTRANSACTIONSEQ", 
            rec."SUBLINENUMBER", 
            rec."TENANTID",
            rec."UNITTYPEFORLINENUMBER", 
            rec."UNITTYPEFORPREADJUSTEDVALUE", 
            rec."UNITTYPEFORSUBLINENUMBER", 
            rec."UNITTYPEFORVALUE", 
            rec."VALUE",
            error_msg1,
            rec."UNITTYPEFORGENERICNUMBER1", 
            rec."UNITTYPEFORGENERICNUMBER2",
            rec."UNITTYPEFORGENERICNUMBER3",
            rec."UNITTYPEFORGENERICNUMBER4",
            rec."UNITTYPEFORGENERICNUMBER5",
            rec."GENERICATTRIBUTE22",
            rec."GENERICATTRIBUTE23",
            rec."GENERICATTRIBUTE24",
            rec."GENERICATTRIBUTE25",
            rec."GENERICATTRIBUTE31",
            rec."GENERICBOOLEAN1",
            rec."GENERICBOOLEAN2"
        );
        
        
        
        
         
        
        END;

        -- Insert the record into the history table
         INSERT INTO ZHISTORYSALESTRANSACTION (
            "BUSINESSUNITNAME", "CHANNEL", "COMMENTS", "COMPENSATIONDATE", "EVENTTYPE", "GENERICATTRIBUTE1", 
              "GENERICATTRIBUTE12", "GENERICATTRIBUTE2",  "GENERICATTRIBUTE27", "GENERICATTRIBUTE28", 
            "GENERICATTRIBUTE29", "GENERICATTRIBUTE3", "GENERICATTRIBUTE30","GENERICATTRIBUTE6",
            "GENERICNUMBER1", "GENERICNUMBER2", "GENERICNUMBER3", "GENERICNUMBER4", "GENERICNUMBER5",  "ISRUNNABLE", "LINENUMBER", "MODIFICATIONDATE", "ORDERID", "ORIGINTYPEID", "PREADJUSTEDVALUE", 
             "PRODUCTID",  "SALESTRANSACTIONSEQ", "SUBLINENUMBER", "TENANTID", 
             "UNITTYPEFORLINENUMBER", 
            "UNITTYPEFORPREADJUSTEDVALUE", "UNITTYPEFORSUBLINENUMBER", "UNITTYPEFORVALUE", "VALUE","UNITTYPEFORGENERICNUMBER1","UNITTYPEFORGENERICNUMBER2","UNITTYPEFORGENERICNUMBER3","UNITTYPEFORGENERICNUMBER4","UNITTYPEFORGENERICNUMBER5",
            "GENERICATTRIBUTE22","GENERICATTRIBUTE23","GENERICATTRIBUTE24","GENERICATTRIBUTE25","GENERICATTRIBUTE31","GENERICBOOLEAN1","GENERICBOOLEAN2"
        )
        VALUES (
            rec."BUSINESSUNITNAME",
            rec."CHANNEL",
            rec."COMMENTS",
            rec."COMPENSATIONDATE", 
            rec."EVENTTYPE", 
            rec."GENERICATTRIBUTE1", 
            rec."GENERICATTRIBUTE12",
            rec."GENERICATTRIBUTE2",
            'MOVED', 
            rec."GENERICATTRIBUTE28", 
            rec."GENERICATTRIBUTE29", 
            rec."GENERICATTRIBUTE3", 
            rec."GENERICATTRIBUTE30",
            rec."GENERICATTRIBUTE6",
            rec."GENERICNUMBER1", 
            rec."GENERICNUMBER2", 
            rec."GENERICNUMBER3", 
            rec."GENERICNUMBER4", 
            rec."GENERICNUMBER5", 
            rec."ISRUNNABLE", 
            rec."LINENUMBER", 
            rec."MODIFICATIONDATE", 
            rec."ORDERID", 
            rec."ORIGINTYPEID", 
            rec."PREADJUSTEDVALUE",
            rec."PRODUCTID",
            rec."SALESTRANSACTIONSEQ", 
            rec."SUBLINENUMBER", 
            rec."TENANTID",
            rec."UNITTYPEFORLINENUMBER", 
            rec."UNITTYPEFORPREADJUSTEDVALUE", 
            rec."UNITTYPEFORSUBLINENUMBER", 
            rec."UNITTYPEFORVALUE", 
            rec."VALUE",
            rec."UNITTYPEFORGENERICNUMBER1", 
            rec."UNITTYPEFORGENERICNUMBER2",
            rec."UNITTYPEFORGENERICNUMBER3",
            rec."UNITTYPEFORGENERICNUMBER4",
            rec."UNITTYPEFORGENERICNUMBER5",
            rec."GENERICATTRIBUTE22",
            rec."GENERICATTRIBUTE23",
            rec."GENERICATTRIBUTE24",
            rec."GENERICATTRIBUTE25",
            rec."GENERICATTRIBUTE31",
            rec."GENERICBOOLEAN1",
            rec."GENERICBOOLEAN2"
        );
        -- Delete the record from the main table if moved successfully
        
        
        
        INSERT INTO #temp_table (
           "BUSINESSUNITNAME", "CHANNEL", "COMMENTS", "COMPENSATIONDATE", "EVENTTYPE", "GENERICATTRIBUTE1", 
              "GENERICATTRIBUTE12", "GENERICATTRIBUTE2",  "GENERICATTRIBUTE27","GENERICATTRIBUTE22","GENERICATTRIBUTE23","GENERICATTRIBUTE24","GENERICATTRIBUTE25", "GENERICATTRIBUTE28", "GENERICATTRIBUTE31","GENERICBOOLEAN1","GENERICBOOLEAN2",
            "GENERICATTRIBUTE29", "GENERICATTRIBUTE3", "GENERICATTRIBUTE30","GENERICATTRIBUTE6",
            "GENERICNUMBER1", "GENERICNUMBER2", "GENERICNUMBER3", "GENERICNUMBER4", "GENERICNUMBER5",  "ISRUNNABLE", "LINENUMBER", "MODIFICATIONDATE", "ORDERID", "ORIGINTYPEID", "PREADJUSTEDVALUE", 
             "PRODUCTID",  "SALESTRANSACTIONSEQ", "SUBLINENUMBER", "TENANTID", 
             "UNITTYPEFORLINENUMBER", 
            "UNITTYPEFORPREADJUSTEDVALUE", "UNITTYPEFORSUBLINENUMBER", "UNITTYPEFORVALUE", "VALUE","UNITTYPEFORGENERICNUMBER1","UNITTYPEFORGENERICNUMBER2","UNITTYPEFORGENERICNUMBER3","UNITTYPEFORGENERICNUMBER4","UNITTYPEFORGENERICNUMBER5"
             
        )
        VALUES (
            rec."BUSINESSUNITNAME",
            rec."CHANNEL",
            rec."COMMENTS",
            rec."COMPENSATIONDATE", 
            rec."EVENTTYPE", 
            rec."GENERICATTRIBUTE1", 
            rec."GENERICATTRIBUTE12",
            rec."GENERICATTRIBUTE2",
            'MOVED', 
            rec."GENERICATTRIBUTE22",
            rec."GENERICATTRIBUTE23",
            rec."GENERICATTRIBUTE24",
            rec."GENERICATTRIBUTE25",
            rec."GENERICATTRIBUTE28",
            rec."GENERICATTRIBUTE31",
            rec."GENERICBOOLEAN1",
            rec."GENERICBOOLEAN2", 
            rec."GENERICATTRIBUTE29", 
            rec."GENERICATTRIBUTE3", 
            rec."GENERICATTRIBUTE30",
            rec."GENERICATTRIBUTE6",
            rec."GENERICNUMBER1", 
            rec."GENERICNUMBER2", 
            rec."GENERICNUMBER3", 
            rec."GENERICNUMBER4", 
            rec."GENERICNUMBER5", 
            rec."ISRUNNABLE", 
            rec."LINENUMBER", 
            rec."MODIFICATIONDATE", 
            rec."ORDERID", 
            rec."ORIGINTYPEID", 
            rec."PREADJUSTEDVALUE",
            rec."PRODUCTID",
            rec."SALESTRANSACTIONSEQ", 
            rec."SUBLINENUMBER", 
            rec."TENANTID",
            rec."UNITTYPEFORLINENUMBER", 
            rec."UNITTYPEFORPREADJUSTEDVALUE", 
            rec."UNITTYPEFORSUBLINENUMBER", 
            rec."UNITTYPEFORVALUE", 
            rec."VALUE",
            rec."UNITTYPEFORGENERICNUMBER1", 
            rec."UNITTYPEFORGENERICNUMBER2",
            rec."UNITTYPEFORGENERICNUMBER3",
            rec."UNITTYPEFORGENERICNUMBER4",
            rec."UNITTYPEFORGENERICNUMBER5"
        );
        
        DELETE FROM HABIB.ZSALESTRANSACTION_ERROR
        WHERE "SALESTRANSACTIONSEQ" = rec."SALESTRANSACTIONSEQ" ;
       
		
    END FOR;






	result_data =
        SELECT    "BUSINESSUNITNAME", "CHANNEL", "COMMENTS", "COMPENSATIONDATE", "EVENTTYPE", "GENERICATTRIBUTE1", 
              "GENERICATTRIBUTE12", "GENERICATTRIBUTE2",  "GENERICATTRIBUTE27","GENERICATTRIBUTE22","GENERICATTRIBUTE23","GENERICATTRIBUTE24","GENERICATTRIBUTE25", "GENERICATTRIBUTE28", "GENERICATTRIBUTE31","GENERICBOOLEAN1","GENERICBOOLEAN2",
            "GENERICATTRIBUTE29", "GENERICATTRIBUTE3", "GENERICATTRIBUTE30","GENERICATTRIBUTE6",
            "GENERICNUMBER1", "GENERICNUMBER2", "GENERICNUMBER3", "GENERICNUMBER4", "GENERICNUMBER5",  "ISRUNNABLE", "LINENUMBER", "MODIFICATIONDATE", "ORDERID", "ORIGINTYPEID", "PREADJUSTEDVALUE", 
             "PRODUCTID",  "SALESTRANSACTIONSEQ", "SUBLINENUMBER", "TENANTID", "UNITTYPEFORLINENUMBER", 
            "UNITTYPEFORPREADJUSTEDVALUE", "UNITTYPEFORSUBLINENUMBER", "UNITTYPEFORVALUE", "VALUE","UNITTYPEFORGENERICNUMBER1","UNITTYPEFORGENERICNUMBER2","UNITTYPEFORGENERICNUMBER3","UNITTYPEFORGENERICNUMBER4","UNITTYPEFORGENERICNUMBER5"
             
            FROM #temp_table;
    -- Close the cursor
			drop table #temp_table;
    CLOSE cur;
    
     

END;